baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "lowRISC: Collaborative open silicon engineering"

# Do not include generator meta-tag in HTML
disableHugoGeneratorInject = true

# RSS, categories and tags disabled for an easy start
# See configuration options for more details:
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["taxonomy", "taxonomyTerm"]

# Fail if links are broken. Switch to WARNING to only warn about it.
refLinksErrorLevel = "ERROR"

timeout = 30000 #ms

googleAnalytics="UA-53520714-1"

[security.funcs]
getenv = ['^HUGO_', 'CONTEXT']

[blackfriday]
plainIDAnchors = false

[permalinks]
blog="/blog/:year/:month/:slug"

# Turn off RSS except for home
[outputs]
home = ["html", "RSS"]
section = ["html"]
taxonomyTerm = ["html"]
taxonomy = ["html"]

[[menu.main]]
  url = "/our-work"
  name = "Our work"
  weight = 20

[[menu.main]]
  url = "/jobs"
  name = "Jobs"
  weight = 35

[[menu.main]]
  url = "/community"
  name = "Community"
  weight = 22

[[menu.main]]
  url = "/open-silicon"
  name = "Open Silicon"
  weight = 21

[[menu.main]]
  url = "/blog"
  name = "Blog"
  weight = 30

[[menu.main]]
  url = "/about"
  name = "About us"
  weight = 40
